### ISSUE TITLE
once matchbutton is clicked to give the first cocktails, if you refresh the page, it provides another movie/cocktail match when it shouldnt.

### ISSUE THREAD

**Issue by ResonantDevotion** [ResonantDevotion/MovieSlashCocktailParty#65]

**Comment by ResonantDevotion** [comment]
Added everyone in this but whoever fixes first can just reassign themselves

**Comment by Bcott93** [comment]
This has been fixed(ish). It works UNTIL a saved recipe is in local storage. I have commented it in the code as such: "
// clears the page upon refresh (will not clear after the save recipe function for improved user experience)"
